#! /bin/sh

# This script is used to verify that the Debian packet gets the
# same version number that the source code has.

ACTUAL_VERSION_NUMBER=`cat debian/VERSION`

# Check the version number of the changelog

if [ -z "`head -1 debian/changelog | grep $ACTUAL_VERSION_NUMBER`" ]; then
    echo Error: \'changelog\' should start with an entry for the current version \($ACTUAL_VERSION_NUMBER\)
    exit 1
    
#else
#    echo changelog ok

fi
